### 课程查询列表
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

### 分类节点查询列表
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员12345612",
  "tags": "",
  "grade": "204001",
  "description": ""

}

### 根据课程id查询课程信息
GET {{content_host}}/content/course/122

### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 122,
  "name": "flutter",
  "users": "所有的学习编程的大小朋友123456。",
  "tags": "flutter从入门到入土123456",
  "mt": "1-2",
  "st": "1-2-8",
  "grade": "204001",
  "teachmode": "200002",
  "description": "一个月让你成为flutter开发大佬。",
  "pic": "",
  "charge": "201001",
  "price": 188.0,
  "qq": "154796811013456",
  "wechat": "18339407112",
  "phone": "18339407112"
}

### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/74/tree-nodes


